name: API Testing Workflow

on:
  push:
    branches:
      - main  # Run this workflow when code is pushed to 'main'
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest  # Change if needed (e.g., ubuntu-22.04)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have this file with dependencies

      - name: Run API Tests
        run: pytest --alluredir=reports  # Run tests and generate Allure reports

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4  # Corrected version
        with:
          name: allure-report
          path: reports  # Ensure 'reports' directory exists
