name: API Testing CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python3
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run API Tests
      run: pytest --alluredir=reports

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: reports
